export { ListOutlet } from './view/list_outlet_view'
export { AddOutlet } from './view/add_outlet_view'
export { DetailOutlet } from './view/detail_outlet_view'
export { EditOutlet } from './view/edit_outlet_view'
export { ListOutletType } from './view/list_outlet_type'
export { AddOutletType } from './view/add_outlet_type'