export {ListClientView} from "./view/list_client_view"
export {CreateProjectsView} from "./view/create_projects_view"
export {AddAssetsView} from "./view/add_assets_view"
export {DetailAddAssetsView} from "./view/detail_add_assets_view"
export {UpdateProjectView} from "./view/update_project_view"
